name: AutorunCommands
main: littlegruz.autoruncommands.CommandMain
version: 2.1
commands:
   setclickcommand:
      description: Binds a command to the player when they right click on a player
      usage: /setclickcommand <identifier>
   displayclickcommand:
      description: Shows the command associated with the player
      usage: /displayclickcommand
   removeclickcommand:
      description: Removes the player from the player click list
      usage: /removeclickcommand
   setcommandblock:
      description: The next block right clicked will be a command block
      usage: /setcommandblock <identifier>
   addacommand:
      description: Add a command to into the map of commands
      usage: /addacommand <identifier> <command> [args]