name: AutorunCommands
main: littlegruz.autoruncommands.CommandMain
author: LittleGruz
website: http://www.littlegruz.com
version: 3.2.3
commands:
   setclickcommand:
      description: Binds a command to the player for when they right click on a player
      usage: /setclickcommand <identifier> [player_name]
   displayclickcommand:
      description: Shows the command associated with the player
      usage: /displayclickcommand
   displaydeathcommand:
      description: Shows the command associated with the player upon death
      usage: /displaydeathcommand
   displayrespawncommand:
      description: Shows the command associated with the player upon respawn
      usage: /displaydeathcommand
   removeclickcommand:
      description: Removes the player from the player click list
      usage: /removeclickcommand [player_name]
   setcommandblock:
      description: The next block right clicked will be a command block
      usage: /setcommandblock <identifier>
   displaycommandblocks:
      description: Lists the locations and identifiers of all command blocks
      usage: /displaycommandblocks
   addacommand:
      description: Add a command to into the map of commands
      usage: /addacommand <identifier> <command> [args]
   displaycommands:
      description: Lists all of the commands with their identifier
      usage: /displaycommands
   addopcommand:
      description: Add an op command to into the map of commands
      usage: /addopcommand <identifier> <command> [args]
   setdeathcommand:
      description: Binds a command to the player for when they die
      usage: /setdeathcommand <identifier> [player_name]
   removedeathcommand:
      description: Removes a command from the player for when they die
      usage: /removedeathcommand [player_name]
   setrespawncommand:
      description: Binds a command to the player for when they respawn
      usage: /setrespawncommand <identifier> [player_name]
   removerespawncommand:
      description: Removes a command from the player for when they respawn
      usage: /removerespawncommand [player_name]
   addstartupcommand:
      description: Add a command to run at server start up
      usage: /addstartupcommand <identifier>
   removestartupcommand:
      description: Removes a command from running at server start up
      usage: /removestartupcommand <identifier>
   displaystartupcommands:
      description: Display the commands that run at server start up
      usage: /displaystartupcommands
   removeacommand:
      description: Removes a command from the map of commands
      usage: /removeacommand <identifier>
   addrepeatcommand:
      description: Add a command to run at regular intervals
      usage: /addrepeatcommand <identifier> <time_interval>
   removerepeatcommand:
      description: Removes a command from running at intervals
      usage: /removerepeatcommand <identifier>
   displayrepeatcommands:
      description: Display the commands that run at intervals
      usage: /displayrepeatcommands
   addjoincommand:
      description: Set a command to run when a player joins
      usage: /addjoincommand <identifier>
   addfirstjoincommand:
      description: Set a command to run when a player first joins
      usage: /addfirstjoincommand <identifier>
   removejoincommand:
      description: Removes a command from running when a player joins
      usage: /removejoincommand <identifier>
   displayjoincommands:
      description: Display the command that runs when a player joins
      usage: /displayjoincommand
   reloadautorunconfig:
      description: Reload config file
      usage: /reloadautorunconfig
   togglefirstjoincommands:
      description: Toggles whether or not first server join commands run
      usage: /togglefirstjoincommands
   setjoincommanddelay:
      description: Sets the delay time for join commands
      usage: /setjoincommanddelay <delay>
permissions:
   autoruncommands.*:
      description: All the AutorunCommand commands
      default: op
   autoruncommands.displayclick:
      description: Shows the command associated with the player
      default: true
   autoruncommands.displaydeath:
      description: Shows the command associated with the player upon death
      default: true
   autoruncommands.displayjoin:
      description: Shows the command that runs when a player joins
      default: true
softdepend: [Multiverse-Core, My Worlds, MultiWorld]