name: AutorunCommands
main: littlegruz.autoruncommands.CommandMain
version: 2.7.2
commands:
   setclickcommand:
      description: Binds a command to the player for when they right click on a player
      usage: /setclickcommand <identifier> [player_name]
   displayclickcommand:
      description: Shows the command associated with the player
      usage: /displayclickcommand
   displaydeathcommand:
      description: Shows the command associated with the player upon death
      usage: /displaydeathcommand
   displayrespawncommand:
      description: Shows the command associated with the player upon respawn
      usage: /displaydeathcommand
   removeclickcommand:
      description: Removes the player from the player click list
      usage: /removeclickcommand [player_name]
   setcommandblock:
      description: The next block right clicked will be a command block
      usage: /setcommandblock <identifier>
   addacommand:
      description: Add a command to into the map of commands
      usage: /addacommand <identifier> <command> [args]
   addopcommand:
      description: Add an op command to into the map of commands
      usage: /addopcommand <identifier> <command> [args]
   setdeathcommand:
      description: Binds a command to the player for when they die
      usage: /setdeathcommand <identifier> [player_name]
   removedeathcommand:
      description: Removes a command from the player for when they die
      usage: /removedeathcommand [player_name]
   setrespawncommand:
      description: Binds a command to the player for when they respawn
      usage: /setrespawncommand <identifier> [player_name]
   removerespawncommand:
      description: Removes a command from the player for when they respawn
      usage: /removerespawncommand [player_name]
   addstartupcommand:
      description: Add a command to run at server start up
      usage: /addstartupcommand <identifier>
   removestartupcommand:
      description: Remove a command from running at server start up
      usage: /removestartupcommand <identifier>
   displaystartupcommands:
      description: Display the commands that run at server start up
      usage: /displaystartupcommands
   removeacommand:
      description: Remove a command from the map of commands
      usage: /removeacommand <identifier>
   addrepeatcommand:
      description: Add a command to run at server start up
      usage: /addrepeatcommand <identifier> <time_interval>
   removerepeatcommand:
      description: Remove a command from running at server start up
      usage: /removerepeatcommand <identifier>
   setjoincommand:
      description: Add a command to run when a player joins
      usage: /setjoincommand <identifier>
   removejoincommand:
      description: Remove a command from running when a player joins
      usage: /removejoincommand <identifier>
   displayjoincommand:
      description: Display the command that runs when a player joins
      usage: /displayjoincommand
permissions:
   autoruncommands.*:
      description: All the AutorunCommand commands
      default: op
   autoruncommands.displayclick:
      description: Shows the command associated with the player
      default: true
   autoruncommands.displaydeath:
      description: Shows the command associated with the player upon death
      default: true
   autoruncommands.displayjoin:
      description: Shows the command that runs when a player joins
      default: true
softdepend: [Multiverse-Core]